// flow-typed signature: cf06fc6ff6863046bfe3df1669163ce7
// flow-typed version: <<STUB>>/react-page-click_v4.0.2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-page-click'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-page-click' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-page-click/build/react-page-click' {
  declare module.exports: any;
}

declare module 'react-page-click/build/react-page-click.min' {
  declare module.exports: any;
}

declare module 'react-page-click/lib/Component' {
  declare module.exports: any;
}

declare module 'react-page-click/lib/index' {
  declare module.exports: any;
}

declare module 'react-page-click/src/Component' {
  declare module.exports: any;
}

declare module 'react-page-click/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-page-click/build/react-page-click.js' {
  declare module.exports: $Exports<'react-page-click/build/react-page-click'>;
}
declare module 'react-page-click/build/react-page-click.min.js' {
  declare module.exports: $Exports<'react-page-click/build/react-page-click.min'>;
}
declare module 'react-page-click/lib/Component.js' {
  declare module.exports: $Exports<'react-page-click/lib/Component'>;
}
declare module 'react-page-click/lib/index.js' {
  declare module.exports: $Exports<'react-page-click/lib/index'>;
}
declare module 'react-page-click/src/Component.js' {
  declare module.exports: $Exports<'react-page-click/src/Component'>;
}
declare module 'react-page-click/src/index.js' {
  declare module.exports: $Exports<'react-page-click/src/index'>;
}
